on:
  pull_request:
    types: [review_requested, ready_for_review, closed]
  workflow_dispatch:

name: "Post on #trackydev"

jobs:
  post_slack:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{'text':'Changes pushed to ATO. See them here: $GITHUB_REF'}" $SLACK_BOT_TOKEN
